"""OpenAIAgentsSDKComposerImpl - emit Python source using openai-agents SDK.

Strategy: pure-template, deterministic, no LLM. Two-pass agent declaration:
  1. Declare all Agent() with empty handoffs
  2. Wire handoffs in second pass (avoids forward-reference issues)

Compile-time resolution (V2.1.0 W2 enhancement):
  prompt_loader (optional): if provided, triage.system_prompt_id is resolved
    and the rendered template emitted as instructions= literal. Without it,
    we emit a TODO comment + use triage.fallback_message as placeholder.
  atom_loader (optional): if provided, tool atom_ids are looked up and a
    TOOLS_MANIFEST dict emitted with atom metadata (subcategory + io_schema +
    projections). Deploy layer reads it to bind real Python tool functions.

Both loaders are optional to preserve V2.1.0-alpha backward compat.
"""
from __future__ import annotations

import ast
import logging
import re
from textwrap import indent
from typing import Iterable, Optional

from app.core.pipelines.factory.ir.multi_agent import (
    GuardrailSpec,
    HandoffEdge,
    MultiAgentSpec,
    SpecialistSpec,
    TriageSpec,
)

logger = logging.getLogger(__name__)


_VAR_SAFE_RE = re.compile(r"[^a-zA-Z0-9_]+")


def _agent_var(specialist_id: str) -> str:
    """Convert specialist id to safe Python variable name (snake_case + _agent suffix)."""
    safe = _VAR_SAFE_RE.sub("_", specialist_id).strip("_")
    if not safe:
        safe = "agent"
    if safe[0].isdigit():
        safe = "_" + safe
    return f"{safe}_agent"


def _py_str(s: str) -> str:
    """Safe Python string literal (double-quoted, escapes newlines & quotes)."""
    return (
        '"'
        + s.replace("\\", "\\\\")
          .replace('"', '\\"')
          .replace("\n", "\\n")
          .replace("\r", "")
        + '"'
    )


def _py_list_strs(items: Iterable[str], per_line: bool = False) -> str:
    quoted = [_py_str(s) for s in items]
    if not quoted:
        return "[]"
    if per_line:
        body = ",\n    ".join(quoted)
        return "[\n    " + body + ",\n]"
    return "[" + ", ".join(quoted) + "]"


def _emit_imports() -> str:
    return (
        "from __future__ import annotations\n"
        "\n"
        "# Runtime: OpenAI Agents SDK (pip install openai-agents)\n"
        "# Locked per Phase 7 决策记录. To swap runtimes, regenerate via composer.\n"
        "from agents import Agent\n"
    )


def _emit_header_comment(spec: MultiAgentSpec) -> str:
    return (
        "# AUTO-GENERATED by agent-ops MultiAgentComposer (do not edit by hand)\n"
        f"# System:      {spec.name}\n"
        f"# Industry:    {spec.industry.code} {spec.industry.primary}"
        + (f" / {spec.industry.sub}" if spec.industry.sub else "")
        + "\n"
        f"# Scenario:    {spec.industry.business_scenario or 'N/A'}\n"
        f"# Specialists: {len(spec.specialists)}\n"
        f"# Handoffs:    {len(spec.handoffs)}\n"
        f"# Guardrails:  {len(spec.guardrails)}\n"
        f"# Runtime:     {spec.runtime}\n"
    )


def _emit_specialist_decl(s: SpecialistSpec, prompt_id_override: str | None = None) -> str:
    """First-pass declaration; handoffs filled in second pass."""
    var = _agent_var(s.id)
    prompt_marker = (
        f"# TODO: bind prompt asset {prompt_id_override!r} at deploy time"
        if prompt_id_override
        else "# Prompt: deploy-time injection"
    )
    tool_marker = (
        f"# TODO: bind tools {s.tools!r} at deploy time"
        if s.tools
        else "# Tools: none"
    )
    return (
        f"# {s.name} ({s.agent_class})\n"
        f"# {s.description}\n"
        f"{prompt_marker}\n"
        f"{tool_marker}\n"
        f"{var} = Agent(\n"
        f"    name={_py_str(s.name)},\n"
        f"    handoff_description={_py_str(s.description)},\n"
        f"    instructions={_py_str(s.nl_brief)},  # placeholder; replaced via prompt_id at deploy time\n"
        f"    handoffs=[],  # wired in second pass below\n"
        f"    tools=[],     # wired at deploy time from {s.tools!r}\n"
        f")\n"
    )


def _emit_triage_decl(
    triage: TriageSpec,
    specialists: list[SpecialistSpec],
    resolved_prompt: Optional[str] = None,
) -> str:
    valid_ids = {s.id for s in specialists}
    handoff_targets = [t for t in triage.initial_handoff_targets if t in valid_ids]
    handoff_vars = [_agent_var(t) for t in handoff_targets]
    handoff_list = "[" + ", ".join(handoff_vars) + "]" if handoff_vars else "[]"

    if resolved_prompt is not None:
        instructions_value = _py_str(resolved_prompt)
        instructions_trailing_comment = ""
        prompt_comment = f"# Prompt: resolved from {triage.system_prompt_id} at compile time"
    else:
        instructions_value = _py_str(triage.fallback_message)
        instructions_trailing_comment = "  # placeholder; replaced via prompt_id at deploy time"
        prompt_comment = f"# Prompt: {triage.system_prompt_id} (deploy-time injection)"

    return (
        f"# Triage agent (entry point)\n"
        f"{prompt_comment}\n"
        f"triage_agent = Agent(\n"
        f"    name={_py_str(triage.name)},\n"
        f"    instructions={instructions_value},{instructions_trailing_comment}\n"
        f"    handoffs={handoff_list},\n"
        f")\n"
    )


def _emit_tools_manifest(
    specialists: list[SpecialistSpec], atom_metadata: dict[str, dict] | None
) -> str:
    """Emit per-specialist tool manifest. atom_metadata=None -> placeholder list."""
    if atom_metadata is None or not any(s.tools for s in specialists):
        return "TOOLS_MANIFEST: dict[str, list[dict]] = {}\n"

    lines = ["# Tools manifest: deploy layer binds real Python functions per atom_id"]
    lines.append("TOOLS_MANIFEST: dict[str, list[dict]] = {")
    for s in specialists:
        if not s.tools:
            continue
        var_key = _agent_var(s.id)
        lines.append(f"    {_py_str(var_key)}: [")
        for atom_id in s.tools:
            meta = atom_metadata.get(atom_id, {"asset_id": atom_id, "resolved": False})
            lines.append(
                "        {"
                + f"\"asset_id\": {_py_str(atom_id)}, "
                + f"\"subcategory\": {_py_str(meta.get('subcategory', 'unknown'))}, "
                + f"\"resolved\": {meta.get('resolved', False)!r}"
                + "},"
            )
        lines.append("    ],")
    lines.append("}\n")
    return "\n".join(lines)


def _emit_handoff_wiring(specialists: list[SpecialistSpec]) -> str:
    """Second-pass: wire each specialist's handoffs (now that all declared)."""
    lines: list[str] = ["# Second pass: wire specialist handoffs after all agents declared"]
    valid_ids = {s.id for s in specialists}
    for s in specialists:
        targets = [t for t in s.handoff_targets if t in valid_ids]
        if not targets:
            continue
        var = _agent_var(s.id)
        target_vars = [_agent_var(t) for t in targets]
        lines.append(f"{var}.handoffs = [{', '.join(target_vars)}]")
    return "\n".join(lines) + "\n"


def _emit_handoff_metadata(handoffs: list[HandoffEdge]) -> str:
    """Emit explicit HandoffEdge metadata as a module dict for runtime introspection."""
    if not handoffs:
        return "HANDOFF_RULES: list[dict] = []\n"
    lines = ["HANDOFF_RULES: list[dict] = ["]
    for h in handoffs:
        lines.append(
            "    {"
            + f"\"from\": {_py_str(h.from_specialist)}, "
            + f"\"to\": {_py_str(h.to_specialist)}, "
            + f"\"when\": {_py_str(h.when)}"
            + "},"
        )
    lines.append("]\n")
    return "\n".join(lines)


def _emit_guardrails(guardrails: list[GuardrailSpec]) -> str:
    """Emit guardrail metadata (deploy-time wires actual @input_guardrail decorators)."""
    if not guardrails:
        return "GUARDRAILS: list[dict] = []\n"
    lines = ["# Guardrails (deploy-time wires actual @input_guardrail decorators)"]
    lines.append("GUARDRAILS: list[dict] = [")
    for g in guardrails:
        lines.append(
            "    {"
            + f"\"kind\": {_py_str(g.kind)}, "
            + f"\"description\": {_py_str(g.description)}, "
            + f"\"blocking\": {g.blocking!r}"
            + "},"
        )
    lines.append("]\n")
    return "\n".join(lines)


def _emit_shared_context(spec: MultiAgentSpec) -> str:
    if not spec.shared_context:
        return "SHARED_CONTEXT_FIELDS: list[dict] = []\n"
    lines = ["SHARED_CONTEXT_FIELDS: list[dict] = ["]
    for c in spec.shared_context:
        lines.append(
            "    {"
            + f"\"name\": {_py_str(c.name)}, "
            + f"\"type\": {_py_str(c.type)}, "
            + f"\"description\": {_py_str(c.description)}, "
            + f"\"initial_value\": {c.initial_value!r}"
            + "},"
        )
    lines.append("]\n")
    return "\n".join(lines)


def _emit_exports(specialists: list[SpecialistSpec]) -> str:
    specialist_vars = [_agent_var(s.id) for s in specialists]
    return (
        "ENTRY_AGENT = triage_agent\n"
        "ALL_AGENTS = [triage_agent, " + ", ".join(specialist_vars) + "]\n"
        "SPECIALIST_AGENTS = [" + ", ".join(specialist_vars) + "]\n"
    )


class OpenAIAgentsSDKComposerImpl:
    """Default composer for V2.1.0: emits openai-agents Python source.

    V2.1.0 W1 (V2.0.5 release): pure-template, no resolvers.
    V2.1.0 W2 (this): optional prompt_loader + atom_loader for compile-time
                      resolution. Backward compatible — both loaders default None.
    """

    def __init__(
        self,
        prompts: Optional[dict] = None,  # dict[str, PromptDef] (asset_id -> PromptDef)
        atoms: Optional[dict] = None,    # dict[str, AtomDef]   (asset_id -> AtomDef)
    ) -> None:
        """
        Args:
            prompts: lookup table for prompt_id resolution. Build via
                     PromptLoaderImpl().load_all(prompts_dir). None = skip resolution.
            atoms:   lookup table for atom_id resolution. Build via
                     AtomLoaderImpl().load_all(atoms_dir). None = skip resolution.
        """
        self._prompts = prompts or {}
        self._atoms = atoms or {}

    def compile(self, spec: MultiAgentSpec) -> str:
        if spec.runtime != "openai_agents_sdk":
            raise ValueError(
                f"OpenAIAgentsSDKComposerImpl only supports runtime='openai_agents_sdk', "
                f"got {spec.runtime!r}"
            )
        issues = spec.validate_graph()
        if issues:
            raise ValueError(f"refusing to compile spec with structural issues: {issues}")

        # Compile-time resolution (V2.1.0 W2)
        resolved_triage_prompt = self._resolve_prompt(spec.triage.system_prompt_id)
        atom_metadata = self._resolve_tools(spec)

        sections: list[str] = [
            _emit_header_comment(spec),
            _emit_imports(),
            "",
            "# ---- Specialists (declared first; handoffs wired below) ----",
            "",
        ]
        for s in spec.specialists:
            sections.append(_emit_specialist_decl(s))
        sections.append("# ---- Triage (entry point) ----\n")
        sections.append(_emit_triage_decl(spec.triage, spec.specialists, resolved_triage_prompt))
        sections.append("# ---- Handoff wiring ----\n")
        sections.append(_emit_handoff_wiring(spec.specialists))
        sections.append("# ---- Metadata exports (introspection / deploy-time wiring) ----\n")
        sections.append(_emit_handoff_metadata(spec.handoffs))
        sections.append(_emit_guardrails(spec.guardrails))
        sections.append(_emit_shared_context(spec))
        sections.append(_emit_tools_manifest(spec.specialists, atom_metadata))
        sections.append("# ---- Public entry points ----\n")
        sections.append(_emit_exports(spec.specialists))
        body = "\n".join(sections)

        # Sanity: parse the emitted source to fail fast on template bugs.
        try:
            ast.parse(body)
        except SyntaxError as exc:
            raise RuntimeError(
                f"composer produced invalid Python (template bug): {exc}\n--- source ---\n{body}"
            ) from exc

        return body

    def _resolve_prompt(self, prompt_id: str) -> Optional[str]:
        """Look up prompt_id in the prompts dict; return raw template text or None."""
        if not self._prompts or not prompt_id:
            return None
        prompt = self._prompts.get(prompt_id)
        if prompt is None:
            logger.warning("prompt %r not in supplied prompts dict", prompt_id)
            return None
        return getattr(prompt, "template", None)

    def _resolve_tools(self, spec: MultiAgentSpec) -> Optional[dict[str, dict]]:
        """For each tool atom_id across all specialists, look up metadata.

        Returns None when no atoms dict provided (signals "skip TOOLS_MANIFEST").
        Returns {} when atoms dict provided but spec uses no tools.
        Returns dict[atom_id, metadata] when both provided.
        """
        if not self._atoms:
            return None
        all_tool_ids: set[str] = {tid for s in spec.specialists for tid in s.tools}
        if not all_tool_ids:
            return {}
        metadata: dict[str, dict] = {}
        for atom_id in all_tool_ids:
            atom = self._atoms.get(atom_id)
            if atom is None:
                logger.warning("atom %r not in supplied atoms dict", atom_id)
                metadata[atom_id] = {"asset_id": atom_id, "resolved": False}
                continue
            metadata[atom_id] = {
                "asset_id": atom_id,
                "subcategory": getattr(atom, "subcategory", "unknown"),
                "resolved": True,
            }
        return metadata
