"""OpenAIAgentsSDKComposerImpl - emit Python source using openai-agents SDK.

Strategy: pure-template, deterministic, no LLM. Two-pass agent declaration:
  1. Declare all Agent() with empty handoffs
  2. Wire handoffs in second pass (avoids forward-reference issues)

Tool/prompt resolution at compile-time:
  tools: spec lists atom asset_ids; composer emits a placeholder list with
         comments. Real tool function objects are wired by the deployment
         layer (it knows which atoms are loaded and how to expose them).
  prompts: spec references prompt_id; composer emits a TODO comment with
           the id. Deployment-layer hook substitutes the rendered prompt.
"""
from __future__ import annotations

import ast
import re
from textwrap import indent
from typing import Iterable

from app.core.pipelines.factory.ir.multi_agent import (
    GuardrailSpec,
    HandoffEdge,
    MultiAgentSpec,
    SpecialistSpec,
    TriageSpec,
)


_VAR_SAFE_RE = re.compile(r"[^a-zA-Z0-9_]+")


def _agent_var(specialist_id: str) -> str:
    """Convert specialist id to safe Python variable name (snake_case + _agent suffix)."""
    safe = _VAR_SAFE_RE.sub("_", specialist_id).strip("_")
    if not safe:
        safe = "agent"
    if safe[0].isdigit():
        safe = "_" + safe
    return f"{safe}_agent"


def _py_str(s: str) -> str:
    """Safe Python string literal (double-quoted, escapes newlines & quotes)."""
    return (
        '"'
        + s.replace("\\", "\\\\")
          .replace('"', '\\"')
          .replace("\n", "\\n")
          .replace("\r", "")
        + '"'
    )


def _py_list_strs(items: Iterable[str], per_line: bool = False) -> str:
    quoted = [_py_str(s) for s in items]
    if not quoted:
        return "[]"
    if per_line:
        body = ",\n    ".join(quoted)
        return "[\n    " + body + ",\n]"
    return "[" + ", ".join(quoted) + "]"


def _emit_imports() -> str:
    return (
        "from __future__ import annotations\n"
        "\n"
        "# Runtime: OpenAI Agents SDK (pip install openai-agents)\n"
        "# Locked per Phase 7 决策记录. To swap runtimes, regenerate via composer.\n"
        "from agents import Agent\n"
    )


def _emit_header_comment(spec: MultiAgentSpec) -> str:
    return (
        "# AUTO-GENERATED by agent-ops MultiAgentComposer (do not edit by hand)\n"
        f"# System:      {spec.name}\n"
        f"# Industry:    {spec.industry.code} {spec.industry.primary}"
        + (f" / {spec.industry.sub}" if spec.industry.sub else "")
        + "\n"
        f"# Scenario:    {spec.industry.business_scenario or 'N/A'}\n"
        f"# Specialists: {len(spec.specialists)}\n"
        f"# Handoffs:    {len(spec.handoffs)}\n"
        f"# Guardrails:  {len(spec.guardrails)}\n"
        f"# Runtime:     {spec.runtime}\n"
    )


def _emit_specialist_decl(s: SpecialistSpec, prompt_id_override: str | None = None) -> str:
    """First-pass declaration; handoffs filled in second pass."""
    var = _agent_var(s.id)
    prompt_marker = (
        f"# TODO: bind prompt asset {prompt_id_override!r} at deploy time"
        if prompt_id_override
        else "# Prompt: deploy-time injection"
    )
    tool_marker = (
        f"# TODO: bind tools {s.tools!r} at deploy time"
        if s.tools
        else "# Tools: none"
    )
    return (
        f"# {s.name} ({s.agent_class})\n"
        f"# {s.description}\n"
        f"{prompt_marker}\n"
        f"{tool_marker}\n"
        f"{var} = Agent(\n"
        f"    name={_py_str(s.name)},\n"
        f"    handoff_description={_py_str(s.description)},\n"
        f"    instructions={_py_str(s.nl_brief)},  # placeholder; replaced via prompt_id at deploy time\n"
        f"    handoffs=[],  # wired in second pass below\n"
        f"    tools=[],     # wired at deploy time from {s.tools!r}\n"
        f")\n"
    )


def _emit_triage_decl(triage: TriageSpec, specialists: list[SpecialistSpec]) -> str:
    valid_ids = {s.id for s in specialists}
    handoff_targets = [t for t in triage.initial_handoff_targets if t in valid_ids]
    handoff_vars = [_agent_var(t) for t in handoff_targets]
    handoff_list = "[" + ", ".join(handoff_vars) + "]" if handoff_vars else "[]"
    return (
        f"# Triage agent (entry point)\n"
        f"# Prompt: {triage.system_prompt_id} (deploy-time injection)\n"
        f"triage_agent = Agent(\n"
        f"    name={_py_str(triage.name)},\n"
        f"    instructions={_py_str(triage.fallback_message)},  # placeholder; replaced via prompt_id\n"
        f"    handoffs={handoff_list},\n"
        f")\n"
    )


def _emit_handoff_wiring(specialists: list[SpecialistSpec]) -> str:
    """Second-pass: wire each specialist's handoffs (now that all declared)."""
    lines: list[str] = ["# Second pass: wire specialist handoffs after all agents declared"]
    valid_ids = {s.id for s in specialists}
    for s in specialists:
        targets = [t for t in s.handoff_targets if t in valid_ids]
        if not targets:
            continue
        var = _agent_var(s.id)
        target_vars = [_agent_var(t) for t in targets]
        lines.append(f"{var}.handoffs = [{', '.join(target_vars)}]")
    return "\n".join(lines) + "\n"


def _emit_handoff_metadata(handoffs: list[HandoffEdge]) -> str:
    """Emit explicit HandoffEdge metadata as a module dict for runtime introspection."""
    if not handoffs:
        return "HANDOFF_RULES: list[dict] = []\n"
    lines = ["HANDOFF_RULES: list[dict] = ["]
    for h in handoffs:
        lines.append(
            "    {"
            + f"\"from\": {_py_str(h.from_specialist)}, "
            + f"\"to\": {_py_str(h.to_specialist)}, "
            + f"\"when\": {_py_str(h.when)}"
            + "},"
        )
    lines.append("]\n")
    return "\n".join(lines)


def _emit_guardrails(guardrails: list[GuardrailSpec]) -> str:
    """Emit guardrail metadata (deploy-time wires actual @input_guardrail decorators)."""
    if not guardrails:
        return "GUARDRAILS: list[dict] = []\n"
    lines = ["# Guardrails (deploy-time wires actual @input_guardrail decorators)"]
    lines.append("GUARDRAILS: list[dict] = [")
    for g in guardrails:
        lines.append(
            "    {"
            + f"\"kind\": {_py_str(g.kind)}, "
            + f"\"description\": {_py_str(g.description)}, "
            + f"\"blocking\": {g.blocking!r}"
            + "},"
        )
    lines.append("]\n")
    return "\n".join(lines)


def _emit_shared_context(spec: MultiAgentSpec) -> str:
    if not spec.shared_context:
        return "SHARED_CONTEXT_FIELDS: list[dict] = []\n"
    lines = ["SHARED_CONTEXT_FIELDS: list[dict] = ["]
    for c in spec.shared_context:
        lines.append(
            "    {"
            + f"\"name\": {_py_str(c.name)}, "
            + f"\"type\": {_py_str(c.type)}, "
            + f"\"description\": {_py_str(c.description)}, "
            + f"\"initial_value\": {c.initial_value!r}"
            + "},"
        )
    lines.append("]\n")
    return "\n".join(lines)


def _emit_exports(specialists: list[SpecialistSpec]) -> str:
    specialist_vars = [_agent_var(s.id) for s in specialists]
    return (
        "ENTRY_AGENT = triage_agent\n"
        "ALL_AGENTS = [triage_agent, " + ", ".join(specialist_vars) + "]\n"
        "SPECIALIST_AGENTS = [" + ", ".join(specialist_vars) + "]\n"
    )


class OpenAIAgentsSDKComposerImpl:
    """Default composer for V2.1.0: emits openai-agents Python source."""

    def compile(self, spec: MultiAgentSpec) -> str:
        if spec.runtime != "openai_agents_sdk":
            raise ValueError(
                f"OpenAIAgentsSDKComposerImpl only supports runtime='openai_agents_sdk', "
                f"got {spec.runtime!r}"
            )
        issues = spec.validate_graph()
        if issues:
            raise ValueError(f"refusing to compile spec with structural issues: {issues}")

        sections: list[str] = [
            _emit_header_comment(spec),
            _emit_imports(),
            "",
            "# ---- Specialists (declared first; handoffs wired below) ----",
            "",
        ]
        for s in spec.specialists:
            sections.append(_emit_specialist_decl(s))
        sections.append("# ---- Triage (entry point) ----\n")
        sections.append(_emit_triage_decl(spec.triage, spec.specialists))
        sections.append("# ---- Handoff wiring ----\n")
        sections.append(_emit_handoff_wiring(spec.specialists))
        sections.append("# ---- Metadata exports (introspection / deploy-time wiring) ----\n")
        sections.append(_emit_handoff_metadata(spec.handoffs))
        sections.append(_emit_guardrails(spec.guardrails))
        sections.append(_emit_shared_context(spec))
        sections.append("# ---- Public entry points ----\n")
        sections.append(_emit_exports(spec.specialists))
        body = "\n".join(sections)

        # Sanity: parse the emitted source to fail fast on template bugs.
        try:
            ast.parse(body)
        except SyntaxError as exc:
            raise RuntimeError(
                f"composer produced invalid Python (template bug): {exc}\n--- source ---\n{body}"
            ) from exc

        return body
