"""Agent Ops Ontology — canonical objects shared across agents, tools, workflows.

Aligned with blueprint §8. Re-exports from ``app.ontology.objects`` so callers
can write ``from app.ontology import CapabilityContract``.
"""
from __future__ import annotations

from app.ontology.objects import (
    ActionCategory,
    ActivationStatus,
    AgentCard,
    AgentContract,
    AgentExample,
    AgentGenerationMetadata,
    AgentTier,
    ApprovalNode,
    Artifact,
    ArtifactType,
    AuthMode,
    BrandTokens,
    CapabilityContract,
    CodeArtifact,
    CostProfile,
    CostSummary,
    Decision,
    EvalCase,
    EvalOutcome,
    EvalResult,
    GeneratedAsset,
    AssetStatus,
    EventType,
    FailureAction,
    FailurePolicy,
    FileEntry,
    HealthStatus,
    Layer,
    PageBlueprint,
    PolicyDecision,
    RequirementSpec,
    RiskLevel,
    RunEvent,
    RunStatus,
    StepRun,
    SuccessCriterion,
    TaskRun,
    TransportType,
    TriggerType,
    UIBlueprint,
    WorkflowSpec,
    WorkflowStep,
    PricingModel,
    ToolActivation,
    ToolAuthMode,
    ToolCategory,
    ToolContract,
    ToolExample,
    ToolTransport,
    PresetActivation,
    PresetBundle,
    PresetEntryInjection,
    PresetFile,
    PresetFramework,
    ProductType,
    ALL_PRODUCT_TYPES,
    UI_PRODUCT_TYPES,
)

__all__ = [
    "CapabilityContract", "RiskLevel", "ActivationStatus",
    "AgentCard", "TransportType", "AuthMode", "CostProfile", "HealthStatus",
    "AgentContract", "AgentExample", "AgentGenerationMetadata", "AgentTier",
    "WorkflowSpec", "WorkflowStep", "ApprovalNode", "FailurePolicy",
    "SuccessCriterion", "TriggerType", "FailureAction",
    "TaskRun", "StepRun", "RunStatus", "CostSummary",
    "Artifact", "ArtifactType",
    "RunEvent", "EventType", "Layer",
    "PolicyDecision", "Decision", "ActionCategory",
    "EvalCase", "EvalResult", "EvalOutcome",
    "GeneratedAsset", "AssetStatus",
    "RequirementSpec", "PageBlueprint", "BrandTokens",
    "UIBlueprint", "FileEntry", "CodeArtifact",
    # Tool Wiki (Batch C+)
    "ToolContract", "ToolExample", "ToolCategory", "ToolTransport",
    "ToolAuthMode", "ToolActivation", "PricingModel",
    # PresetBundle (Batch C++)
    "PresetBundle", "PresetFile", "PresetEntryInjection",
    "PresetFramework", "PresetActivation",
    # ProductType (Batch C++++)
    "ProductType", "ALL_PRODUCT_TYPES", "UI_PRODUCT_TYPES",
]
