"""DifyCompilerImpl V1 - emits Dify-flavored YAML from ResolvedDAG.

V1 simplification: emits a workflow YAML structure roughly matching Dify's
exported app format (app + workflow.graph.nodes + workflow.graph.edges).
Each node type is a coarse mapping; exact Dify YAML tuning happens once we
have a sandbox to import into.

PURE TEMPLATE-BASED: NO LLM call here. Determinism is the entire point.
Same ResolvedDAG -> same YAML output every time.

Phase 1 W3 day 1-2: refine projections per atom against real Dify YAML schema.
Phase 1 W3 day 3: read atom.projections.dify.template (Jinja2) instead of hardcoded.
"""

from __future__ import annotations

from typing import Any

import yaml

from app.core.pipelines.factory.ir import ResolvedDAG, ResolvedNode
from app.core.trace.bus import emit
from app.registry.atom_loader import AtomDef, AtomLoaderImpl


_NODE_TYPE_MAP = {
    "DB": "code",
    "HTTP": "http-request",
    "LLM": "llm",
    "Notify": "http-request",
    "Schedule": "scheduler",
    "OCR": "tool",
    "TTS": "tool",
    "ASR": "tool",
    "VectorDB": "tool",
    "Embedding": "tool",
    "DocParser": "tool",
    "Chart": "code",
    "WebSearch": "tool",
}


class DifyCompilerImpl:
    """V1 compiler. Output is Dify-shaped YAML; refine in Phase 1 W3."""

    def __init__(self, atom_loader: AtomLoaderImpl | None = None) -> None:
        self._atoms_by_id: dict[str, AtomDef] = {}
        if atom_loader is not None:
            self._loader = atom_loader

    def index(self, atoms: dict[str, AtomDef]) -> None:
        self._atoms_by_id = atoms

    def compile(self, dag: ResolvedDAG) -> str:
        if dag.target not in ("dify", "hybrid"):
            raise ValueError(
                f"DifyCompilerImpl only handles dify/hybrid targets, got {dag.target}"
            )

        emit(
            "L3",
            "DifyCompiler",
            "compile_start",
            f"target={dag.target} nodes={len(dag.nodes)}",
        )

        scoped_nodes = self._scope_nodes(dag)
        scoped_edges = self._scope_edges(dag, scoped_nodes)

        rendered_nodes = [self._render_node(n) for n in scoped_nodes]

        app_dict: dict[str, Any] = {
            "app": {
                "name": f"specimen_{dag.intent_ref[:30]}",
                "mode": "workflow",
                "description": f"Generated by agent-ops V2.0.0 factory; target={dag.target}",
            },
            "workflow": {
                "graph": {
                    "nodes": rendered_nodes,
                    "edges": [
                        {
                            "id": f"{e.from_node}->{e.to_node}",
                            "source": e.from_node,
                            "target": e.to_node,
                            "data": {
                                "from_var": e.from_var,
                                "to_var": e.to_var,
                                "type_check": {
                                    "from": e.type_check.from_type,
                                    "to": e.type_check.to_type,
                                },
                                "needs_adapter": e.needs_adapter,
                            },
                        }
                        for e in scoped_edges
                    ],
                },
                "factory_metadata": {
                    "intent_ref": dag.intent_ref,
                    "pattern_id": dag.pattern_id,
                    "target": dag.target,
                    "issues": dag.issues,
                },
            },
        }
        out = yaml.safe_dump(
            app_dict, allow_unicode=True, sort_keys=False, default_flow_style=False
        )
        emit(
            "L3",
            "DifyCompiler",
            "compile_done",
            f"yaml_chars={len(out)} nodes={len(rendered_nodes)}",
        )
        return out

    def _scope_nodes(self, dag: ResolvedDAG) -> list[ResolvedNode]:
        if dag.target == "dify":
            return list(dag.nodes)
        if dag.target_split:
            ids = set(dag.target_split.get("dify_nodes", []))
            return [n for n in dag.nodes if n.id in ids]
        return list(dag.nodes)

    def _scope_edges(self, dag, scoped_nodes):
        ids = {n.id for n in scoped_nodes}
        return [e for e in dag.edges if e.from_node in ids and e.to_node in ids]

    def _render_node(self, node: ResolvedNode) -> dict[str, Any]:
        atom = self._atoms_by_id.get(node.asset_id)
        subcategory = atom.subcategory if atom else "Unknown"
        node_type = _NODE_TYPE_MAP.get(subcategory, "code")

        data: dict[str, Any] = {
            "title": atom.name if atom else node.asset_id,
            "asset_id": node.asset_id,
            "asset_version": node.asset_version,
            "selection_reason": node.selection_reason,
            "confidence": node.confidence,
            "inputs": node.inputs,
            "params": node.params,
        }
        if subcategory == "LLM":
            data["llm_routing"] = {
                "task_type": node.llm_task_type,
                "size": node.llm_size,
                "fallback_chain": node.llm_fallback_chain,
                "model_placeholder": (
                    f"${{RUIDONG_MODEL_FOR_{(node.llm_task_type or '').replace(' ', '_').replace('/', '')}_{node.llm_size or ''}}}"
                ),
            }
            if node.prompt_id:
                data["prompt_id"] = node.prompt_id
        return {
            "id": node.id,
            "type": node_type,
            "data": data,
        }
